#!/bin/bash

VERSIONRESOURCE=res/values/version.xml
VERSIONPACKAGE=src\main\java\de\unikl\hci\abbas\behaviometric\TouchLogger\utils
VERSIONCLASS=$VERSIONPACKAGE/Version.java

BUILD=`git describe --all --long | cut -d "-" -f 3`
DATE=`date +"%Y-%m-%d_%R"` 

# Generate the Version class
if [[ ! -d $VERSIONPACKAGE ]]; then
mkdir $VERSIONPACKAGE;
fi

echo -e "de.unikl.hci.abbas.touchscreenlogger.version;

// DO NOT MODIFY -- AUTOMATICALLY GENERATED BY scripts/versiondate.sh
public class Version {
    public static final String BUILD = \"$BUILD\";
    public static final String DATE = \"$DATE\";
}" > $VERSIONCLASS


# Generate the version resource
echo -e "<?xml version=\"1.0\" encoding=\"utf-8\"?>
<resources>
	<!-- Automatically generated by scripts/versiondate.sh -->
    <string name=\"about_build\">$BUILD</string>
    <string name=\"about_date\">$DATE</string>
</resources>" > $VERSIONRESOURCE
